name: autofix.ci # needed to securely identify the workflow

on:
  pull_request:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - uses: autofix-ci/action@bee19d72e71787c12ca0f29de72f2833e437e4c9
        with:
          commit-message: "chore: apply automated fixes"
