name: Continuous Releases

on:
  push:
    branches:
      - main
      - dev
      - release-*
    tags-ignore:
      - v*
    paths-ignore:
      - "examples/**"
      - "**/README.md"
  pull_request:
    paths-ignore:
      - "examples/**"
      - "**/README.md"

jobs:
  cr:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build start
        run: pnpm run build && pnpm run types

      - name: Release
        run: pnpm dlx pkg-pr-new@0.0 publish './packages/*' --template './examples/*' --compact 
