name: Release

on:
  push:
    branches:
      - main

permissions:
  pull-requests: write
  contents: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v4


      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install  --no-frozen-lockfile
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: pnpm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: stefanzweifel/git-auto-commit-action@v5
